### ISSUE TITLE
Add capality to import additional config files from a folder

### ISSUE THREAD

**Issue by prigio** [prigio/startainer#1]
Similar to SSHD and other linux deamons, within the main config file it should be possible to include all files present within a given folder. 

The `.dockerstarter.yaml` file could contain a configuration like the following:

```yaml
# include all files within the specified folder
include: path-to-folder

# first container definition, etc
container1:
  image: ...
  run: 
    - ...
  ...
container2: 
```
